[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ziri"
version = "0.2.0"
description = "Ziri — Python shim that invokes the Node CLI (requires Node >=18)"
authors = [{name="Ziri Team"}]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
ziri = "ziri.__main__:run"
